### ISSUE TITLE
Add support for 'ip' field in announce GET

### ISSUE THREAD

**Issue by Miserlou** [webtorrent/bittorrent-tracker#181]
In the [BitTorrent spec](http://www.bittorrent.org/beps/bep_0003.html), it says there should be support for an `ip` field in the announce GET:

```
ip
    An optional parameter giving the IP (or dns name) which this peer is at. Generally used for the origin if it's on the same machine as the tracker.
```

It doesn't look like the bittorrent-tracker client here supports this field, although it does support `port` (I don't know about the server, I only need it for the client but we might as well add it symmetrically.)

If this is available already, it should be added to the documentation.

**Comment by Miserlou** [comment]
This looks easy enough to add in, I can submit a PR once somebody can confirm this issue.

Poking the usual suspects, @yciabaud @DiegoRBaquero

**Comment by Miserlou** [comment]
This may end up being related to #157 depending on the usage.

**Comment by Miserlou** [comment]
Confirming that this isn't supported in the server either: https://github.com/feross/bittorrent-tracker/blob/master/lib/server/parse-http.js#L34

Again, seems like a really simple fix, just want to confirm you'll meet the spec before I send PR.

**Comment by yciabaud** [comment]
I can confirm we want to meet the specs but this field is optional and I don't get the use cases for this. 
Do you think this should be an option in the client? Or you want to provide the private ip?

**Comment by Miserlou** [comment]
I personally just need this as an option in the client, but it looks easy enough in the server code as well. This feature was supported by some other server implementations I just quickly looked at.

My use case is for hidden services, but you could also see it being useful for people who want to seed using dynDNS without having to constantly port-forward/NAT-punch and just run their seedbox on a named address instead, etc.

I don't know what 'optional' means in the BEP, but I think that means that it's optional for the client to provide, not for the tracker to implement. For example, if I announce currently with a supplied hostname, then this tracker doesn't recognized it and just uses the connection's rhost, so I'm going to get inbound peers that I don't want because of the non-BEP compliant server.

**Comment by Miserlou** [comment]
I could imagine this could also be useful to announce permanent/webseeds, ex if I'm a big game studio, I might want to run a seedbox at

seedbox.sega.com:6881

but announce it from my CI at

ci.sega.com:442

With `ip` as an option, we can announce from a CI but send the traffic to the seedbox, not the originating interface of the CI system.

**Comment by yciabaud** [comment]
I agree with you and I believe the server must handle it. The client should also be able to announce it.

IMHO... PR welcome!

**Comment by Miserlou** [comment]
I submitted an initial PR that needs a bit of further discussion, thanks @yciabaud !

**Comment by wI2L** [comment]
@Miserlou @yciabaud I can confirm that this option MUST be treated as optional by the server, meaning it's not mandatory for the client to send it, in this case the final endpoint (ip:port) of the peer is a composition of the ip address from which the request came from and the parameter port (which mandatory, the client MUST send it).

Keep in mind that there is also the params `ipv4` and `ipv6` to keep in mind.
ref: [http://www.bittorrent.org/beps/bep_0007.html](url)

**Comment by Miserlou** [comment]
Hm. BEP07 was never standardized and seems to have some big omissions to me, so I think I'd consider that outside the scope of this issue, although certainly worthy of its own discussion.

**Comment by wI2L** [comment]
@Miserlou Sure thing. Still i think, even if this BEP is prt to the 'Draft BEPS', I do think we can consider it as a standard due to the implementations out there.

**Comment by Miserlou** [comment]
Out of curiosity, can you specify any that you're referring to? I started doing some surveying around this and haven't found a single open tracker that met my criteria: https://github.com/Miserlou/bt-ip-support

**Comment by wI2L** [comment]
Are you looking for implementations of running trackers ?

Based on your criterias, there is [chihaya](https://github.com/chihaya/chihaya), and I think xbtt might fit your need to, not sure about the IP field but you can always check the sources.
