### ISSUE TITLE
Allow websocket trackers for clients without webrtc support

### ISSUE THREAD

**Issue by yciabaud** [webtorrent/bittorrent-tracker#203]
I would like to use my websocket tracker with some node that have no webrtc support (I have a structured announce request that does not fit HTTP and would like to track disconnections).

Do you believe we can serve tcp peers along the ws channel?
I imagine we could switch on basic tracking if we dont include webrtc offers in the announce request.

I can push a PR if you think this might be merged :/

**Comment by DiegoRBaquero** [comment]
Why reimplement TCP/UDP tracking over ws? Why not just use TCP/UDP trackers?

**Comment by yciabaud** [comment]
Because I am using extra params in the announce requests and websocket allows me to handle as much data as I want. HTTP tracker uses URL encoding and it is not well designed for this.
I also like the capability to track when node disconnects in order to have more accurate swarm.
