### ISSUE TITLE
Explanation about the contribution process

### ISSUE THREAD

**Issue by yciabaud** [webtorrent/bittorrent-tracker#207]
@feross, I am bit struggling with this project because it looks like you cannot manage to review the PRs (for instance #157 is 8 month old) 
I guess you don't have time with all the projects you are managing but I need to know if it worth spending some time working here or not.

I am wondering what is your plan for bittorrent-tracker, do you prefer to freeze the new features and maintain existing code or do you want the contributors to merge PRs on their own ? (I believe @DiegoRBaquero and I can make it)

Do you want to release when you got a chance to have a look or could we manage to update the release process to allow contributors to make a new version?

**Comment by DiegoRBaquero** [comment]
I'd like to extend this 'question(?)' to all webtorrent modules.

**Comment by DiegoRBaquero** [comment]
There's more reviewers and active maintenance now :)
