### ISSUE TITLE
"invalid action in Http" error thrown in server

### ISSUE THREAD

**Issue by c060604** [webtorrent/bittorrent-tracker#224]
## Problems
I use the `bittorrent-tracker` package to run a tracker server. But it always throw the error as follows:
```js
invalid action in HTTP request: /?numwant=50&uploaded=0&downloaded=0&event=started&compact=1&info_hash=012345678901234567890&peer_id=01234567890123456789&port=6881
```
I find it is thrown in `bittorrent-tracker/lib/server/parse-http.js`. It checks the `opts` properties and throw the error as follows:

![snip20170719_37](https://user-images.githubusercontent.com/5510945/28350042-dad27e74-6c78-11e7-85fb-d06ba5874f39.png)

![snip20170719_31](https://user-images.githubusercontent.com/5510945/28349562-31236142-6c76-11e7-939a-e1300038a6d1.png)

However, I find that in `bittorrent-tracker/server.js` the `opts` parameter psssing to the `parseHttpRequest` function does not have own property of `action`.

![snip20170719_36](https://user-images.githubusercontent.com/5510945/28350154-83edbd0c-6c79-11e7-8a44-b1773d5b00ad.png)

![snip20170719_38](https://user-images.githubusercontent.com/5510945/28350165-91d1526c-6c79-11e7-9946-21b8fe9efa5a.png)

 
## Environment

`node version`: 5.10.0

`bittorrent-tracker tag`: 9.2.3

**Comment by FrancoisMentec** [comment]
Similar error while trying to add a torrent to the tracker using transmission:
```
Error: invalid action in HTTP request: /?info_hash=%d9v%7f%0a1%a0%c2%a4%1aW%b6%3d%2cA%07%86%00O%8a%f4&peer_id=-TR2920-llfgzkikjb8c&port=51413&uploaded=0&downloaded=0&left=0&numwant=80&key=4339eebc&compact=1&supportcrypto=1&event=started
    at parseHttpRequest (/udd/fmentec/Documents/mytorrent-tracker/node_modules/bittorrent-tracker/lib/server/parse-http.js:55:11)
    at Server.onHttpRequest (/udd/fmentec/Documents/mytorrent-tracker/node_modules/bittorrent-tracker/server.js:383:14)
    at Server.<anonymous> (/udd/fmentec/Documents/mytorrent-tracker/node_modules/bittorrent-tracker/server.js:78:14)
    at emitTwo (events.js:111:20)
    at Server.emit (events.js:194:7)
    at parserOnIncoming (_http_server.js:563:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by fijiwebdesign** [comment]
Did you have /announce at the end of the tracker URL?

eg:

```
var Client = require('bittorrent-tracker')
var opts = {
    peerId: peerId,
    infoHash: torrent.infoHash,
    port: 6881,
    announce: [
      'http://tracker.torcdn.com/announce'
    ], 
  }
 
  var client = new Client(opts)
```

Here I'm running the tracker on http://tracker.torcdn.com/

**Comment by Chocobozzz** [comment]
If your path is not just `/announce` or `/scrape`, you need to add the action parameter like this: https://github.com/Chocobozzz/PeerTube/blob/develop/server.ts#L106

**Comment by DiegoRBaquero** [comment]
Missing 'announce' in the url.
