### ISSUE TITLE
Json call to get stat per torrent

### ISSUE THREAD

**Issue by brambox** [webtorrent/bittorrent-tracker#225]
Hello is it possible and how do i get stats per torrent?
Stats json just show all.
Can you do something like stats.json?infohash=?
Thank you!

**Comment by DiegoRBaquero** [comment]
It's not implemented in the current version, but you can do it on top of it.

**Comment by brambox** [comment]
Thank you!
I see. Is it planed some day?
If it's something that can be  can be implemented will be very nice.
Any  tips?

**Comment by DiegoRBaquero** [comment]
Not really planned. PR welcome.

You can implement it using the `tracker.http.on('request', ...)`. e.g.: https://github.com/webtorrent/webtorrent.io/blob/ee5fc0bf09093d830075578f33ea4d36a5d1bc53/server/tracker.js#L16
