### ISSUE TITLE
WARNING: invalid action in HTTP request

### ISSUE THREAD

**Issue by MichaelSchmidt82** [webtorrent/bittorrent-tracker#227]
I seem to be having an issue running the tracker on an AWS setup (all traffic, all-ports, all destinations open).  When bittorrent-tracker is ran on a machine in local network, the tracker operates fine to other members on the LAN.  On AWS, I seem to be getting this warning from the same clients:

HTTP tracker: http://localhost:8000/announce
UDP tracker: udp://0.0.0.0:8000
UDP6 tracker: udp://localhost:8000
WebSocket tracker: ws://localhost:8000
Tracker stats: http://localhost:8000/stats
WARNING: invalid action in HTTP request: /?info_hash=%a5%28%dc%81%a9%5cZ%80%b3%82%98%f2%81%0c%8dT%13%7d%836&peer_id=-TR2840-gujshgdzm27b&port=50102&uploaded=0&downloaded=0&left=804216&numwant=80&key=5c0b3abe&compact=1&supportcrypto=1&event=started
WARNING: invalid action in HTTP request: /?info_hash=%a5%28%dc%81%a9%5cZ%80%b3%82%98%f2%81%0c%8dT%13%7d%836&peer_id=-TR2840-gujshgdzm27b&port=50102&uploaded=0&downloaded=0&left=804216&numwant=80&key=5c0b3abe&compact=1&supportcrypto=1&event=started

version 9.2.3

This results in error code 0 on the clients signaling an unresponsive tracker.

EDIT:  I am able to access the stats.

**Comment by fijiwebdesign** [comment]
Similar to: https://github.com/webtorrent/bittorrent-tracker/issues/224

You may not have /announce at the end of the tracker URL when using AWS? 

`WARNING: invalid action in HTTP request: /?info_hash=%a5%28%dc%81%a9%5cZ%80%b3%82%98%f2%81%0c%8dT%13%7d%836&peer_id=-TR2840-gujshgdzm27b&port=50102&uploaded=0&downloaded=0&left=804216&numwant=80&key=5c0b3abe&compact=1&supportcrypto=1&event=started`

Should have the proper url: 

`/announce?info_hash=%a5%28%dc%81%a9%5cZ%80%b3%82%98%f2%81%0c%8dT%13%7d%836&peer_id=-TR2840-gujshgdzm27b&port=50102&uploaded=0&downloaded=0&left=804216&numwant=80&key=5c0b3abe&compact=1&supportcrypto=1&event=started`

**Comment by DiegoRBaquero** [comment]
as @fijiwebdesign said, you are missing 'announce' in the url of the torrents/magnets
