### ISSUE TITLE
Use WebSocket/socket.io from express

### ISSUE THREAD

**Issue by gurupras** [webtorrent/bittorrent-tracker#232]
I'm trying to include `bittorrent-tracker` into my `express` app. If my understanding is correct, since my clients are going to use `webtorrent`, I need to set up websocket capabilities for the `bittorrent-tracker` server. To that end, I would like to use the same ports that I do for my `express` app to handle `bittorrent-tracker` requests. I have already looked at #183 and, unfortunately, that is not a solution I can hope for since express-ws seems to have conflicts with `socket.io`.

Is this possible to achieve without resorting to express-ws? Another way I could possibly solve this is by using the `socket` object as means of communicating between the tracker server and clients. Is this possible?

**Comment by Chocobozzz** [comment]
I set up a websocket tracker on my express app like this: https://github.com/Chocobozzz/PeerTube/blob/develop/server.ts#L99. Maybe it will help you.

**Comment by Chocobozzz** [comment]
I use `webtorrent.add` with a magnet URI generated by the server: https://github.com/Chocobozzz/PeerTube/blob/develop/server/models/video/video.ts#L973

**Comment by gurupras** [comment]
I completely forgot I created this issue. For those who end up here facing the same problem, here's what I finally did to solve it.

```
var server = http.createServer()
...

const TrackerServer = require('bittorrent-tracker').Server
const WebSocketServer = require('uws').Server

var trackerServer = new TrackerServer({
  http: false,
  udp: false,
  ws: false,
  dht: false
})

var wss = new WebSocketServer({
  server: http,
  path: '/torrent/ws' // Change this to suit your needs
})
wss.on('connection', function (ws) {
  trackerServer.onWebSocketConnection(ws)
})

trackerServer.on('error', function (err) {
  console.log(err)
})
// Add other tracker events here
```
