### ISSUE TITLE
Scraping issue on http tracker

### ISSUE THREAD

**Issue by drt420** [webtorrent/bittorrent-tracker#233]
Hi
While scraping through http tracker it is giving me all values as 0. Following is the test URL.
http://tracker.nextbit.me/scrape?info_hash=%B8%CE%96%3C%FA%FAkc%A0Y%8A%85%8D%F8u+%C3%96%267

**Comment by feross** [comment]
That URL doesn't load anymore. 
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
