### ISSUE TITLE
Scrape files?

### ISSUE THREAD

**Issue by d33tah** [webtorrent/bittorrent-tracker#239]
Hi!

I'd like to do some research on what kind of data is accessible through the WebTorrent trackers. Some BitTorrent trackers serve files like those mentioned here:

https://stackoverflow.com/a/39822400/1091116

Could you publish such file for this tracker?

Cheers,
d33tah

**Comment by DiegoRBaquero** [comment]
Not implemented, can be easily done, would accept a PR.

**Comment by feross** [comment]
I don't have any immediate plans to work on this issue, so I'm going to close it. If you (or anyone else) wants to tackle it, we'll happily accept a PR!
