### ISSUE TITLE
how bittorrent-tracker running with multiple cpu core??

### ISSUE THREAD

**Issue by dlerorg** [webtorrent/bittorrent-tracker#242]
hello everyone.
i would like to know does bittorrent-tracker support multiple cpu core?
in attachment, only one process running.
![image](https://user-images.githubusercontent.com/34603198/34071791-2ce49210-e2b7-11e7-8fb1-903df6e00799.png)

**Comment by DiegoRBaquero** [comment]
It can't, there's no persistence to any type of storage that allows multiple node processes to run at the same time.

If you want to work in the issue, I'll review your pull request.

You can also take a look at [uws](https://github.com/DiegoRBaquero/uWebTorrentTracker) which is more lightweight, but still not multi-cpu.
