### ISSUE TITLE
Unable to get info without announce

### ISSUE THREAD

**Issue by francoism90** [webtorrent/bittorrent-tracker#247]
Doesn't work:
`magnet:?xt=urn:btih:40448d478d9203a3919b0900e7fbb9e8748dcdf9&dn=ubuntu-17.10-desktop-amd64.iso`

Works:
`magnet:?xt=urn:btih:40448d478d9203a3919b0900e7fbb9e8748dcdf9&dn=ubuntu-17.10-desktop-amd64.iso&tr=http%3a%2f%2ftorrent.ubuntu.com%3a6969%2fannounce&tr=http%3a%2f%2fipv6.torrent.ubuntu.com%3a6969%2fannounce`

**Comment by DiegoRBaquero** [comment]
Default trackers and DHT must not be tracking that torrent
