### ISSUE TITLE
Which one to use?

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/bittorrent-tracker#252]
Hi, I have to choose between this package and the µWS powered one. I only need the tracker to talk with webtorrent-desktop, so I only need the ws/µWS part.

My questions are:
1) Is the µWS version stability the same as this one?
2) Wich one is tracker.btorrent.xyz (and, if you know, also tracker.openwebtorrent.com) using?

Thank you!

**Comment by DiegoRBaquero** [comment]
1. Yes
2. BTorrent is using `uws` one. I don't know about openwebtorrent. @alxhotel ?

**Comment by Ciao121** [comment]
Thank you @DiegoRBaquero

**Comment by alxhotel** [comment]
Currently, OpenWebTorrent uses `bittorrent-tracker`.

**Comment by Ciao121** [comment]
Thank you too @alxhotel

**Comment by feross** [comment]
@DiegoRBaquero Is it worth looking into getting these two packages merged back together? Or is the goal too different? There's an argument to be made either way:

1. Separate – having the spec operating as two implementations ensures that any single implementation isn't the de-facto standard, but rather the spec is the standard.

2. Together – save maintenance effort / confusion for newcomers.

Curious to hear your thoughts. @DiegoRBaquero

**Comment by feross** [comment]
Actually, let's move this discussion to a new issue: https://github.com/webtorrent/bittorrent-tracker/issues/269
