### ISSUE TITLE
Lot of violations

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/bittorrent-tracker#254]
I'm getting lot of violations messages when seeding many files (lets say 100)
`[Violation] 'setInterval' handler took 126ms - \node_modules\bittorrent-tracker\lib\client\tracker.js:25`
Time varies from 100 to 200 most of times. That should means, if I interpret the thing correctly, that if i seed 100 files something between 10 to 20 seconds are needed at every announces "round".

**Comment by Ciao121** [comment]
Maybe I'm wrong. If an update handler has not to wait the previous one to hand (I don't know) I cannot sum those times...

**Comment by feross** [comment]
This warning just means that the function that we run on a periodic basis to announce has taken 126ms to run. That's a browser warning to inform you not to block the event loop for a long time. It's unclear what the cause is, but if you find a solution to make this run faster, PR welcome.
