### ISSUE TITLE
Can't install (gyp WARN EACCES)

### ISSUE THREAD

**Issue by Petr73ru** [webtorrent/bittorrent-tracker#255]
I run : 
  sudo npm i bittorrent-tracker -g
and get :
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/bittorrent-tracker/node_modules/bufferutil/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/bittorrent-tracker/node_modules/bufferutil/.node-gyp/9.4.0"

What happened?

**Comment by DiegoRBaquero** [comment]
Try without sudo

**Comment by Petr73ru** [comment]
I was trying run it on node 9.x.x and get error but on node 4.x.x all just fine!
