### ISSUE TITLE
WebSocket tracker should have a shorter interval <-- Why ?

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/bittorrent-tracker#256]
Hi, I do not understand why WebSocket tracker should have a shorter interval... 
https://github.com/webtorrent/bittorrent-tracker/blob/01c550dac05ed43aeed183b04979ffbba379720d/server.js#L526

Someone can explain this to me?
Thank you!

**Comment by feross** [comment]
@Ciao121 I made this decision because there are usually fewer WebRTC peers, so it improved performance in certain use cases to check for peers more often.
