### ISSUE TITLE
Websocket tracker protocol specification

### ISSUE THREAD

**Issue by mrd0ll4r** [webtorrent/bittorrent-tracker#257]
Hey webtorrent people!

I am one of the [chihaya](https://chihaya.io) devs. We now got multiple people asking if we are gonna implement webtorrent support. I asked about a spec some time ago on IRC but that might've drowned in the recent freenode spam. So now here: When is there gonna be a BEP for the websocket tracker protocol? Do you support IPv4 and IPv6 already? 

I had a look at [lib/server/parse-websocket.js](https://github.com/webtorrent/bittorrent-tracker/blob/master/lib/server/parse-websocket.js), which looks straightforward enough to implement. Are there any other resources we could use?

From what I gathered, webtorrent peers can only connect to other webtorrent peers, i.e. should not receive peers in the announce response that do not support webtorrent. Is there anything else specific about webtorrent peers? Does the protocol support scrapes (yet)?

Crosslink: https://github.com/chihaya/chihaya/issues/388

Cheers

**Comment by feross** [comment]
I would use `parse-websocket.js` until a spec is written. There's an issue to follow here: https://github.com/webtorrent/webtorrent/issues/168 There's an attempt at a spec linked in that issue that can be used until we release an official "blessed" one.
