### ISSUE TITLE
WebSocket tracker URL issue

### ISSUE THREAD

**Issue by valinux** [webtorrent/bittorrent-tracker#264]
When the bittorrent-tracker is started its issuing us with the localhost address and port as well as the network definition for each service running on localhost for example:
HTTP tracker: http://0.0.0.0:8000/announce
UDP tracker: udp://0.0.0.0:8000
UDP6 tracker: udp://0.0.0.0:8000
WebSocket tracker: ws://0.0.0.0:8000
Tracker stats: http://0.0.0.0:8000/stats

why is WebSocket ws:// and not wss:// ? 
this will effect torrent files when we create with our own private trackers for WSS
instant.oi will search for wss but not for ws url please fix this issue!

**Comment by DiegoRBaquero** [comment]
You need to setup a reverse proxy (nginx recommended) that handles the HTTPS (and effectively WSS) with your certificate (I'd recommend Lets Encrypt)

**Comment by valinux** [comment]
Thank you for your quick response!
I did a quick look into the bin file location at /usr/bin/bittorrent-tracker
under:
if (server.ws && !argv.quiet) {
    var wsAddr = server.http.address()
    var wsHost = wsAddr.address !== '::' ? wsAddr.address : 'localhost'
    var wsPort = wsAddr.port
    console.log('WebSocket tracker: ws://' + wsHost + ':' + wsPort)
  }

i edited line WebSocket tracker: ws:// 
to
WebSocket tracker: wss://

I'm not sure if that will make any difference since i'm still testing,
I will try the nginx way as recommended, i saw the example config file inside the bittorrent-tracker folder.
- W1z
