### ISSUE TITLE
Tracker responds with "invalid port"

### ISSUE THREAD

**Issue by nkoep** [webtorrent/bittorrent-tracker#265]
Hey,

I was trying to set up bittorrent-tracker inside a docker container behind a reverse proxy and the tracker constantly kept responding with an "invalid port" error message despite the /stats page listing the peer. So I tried running the command-line version that ships with bittorrent-tracker on my local machine to rule out any issues with the docker setup and strangely enough ran into the same problem:
```
$ node_modules/.bin/bittorrent-tracker --http
HTTP tracker: http://localhost:8000/announce
Tracker stats: http://localhost:8000/stats
start: 127.0.0.1:57702
WARNING: invalid port
```
The torrent I was testing this on was created in deluge with the private flag set and the tracker set as above. I generally don't seem to have any issues with torrents, e.g., I can download and seed an official ubuntu image without any issues or need to bother with port-forwarding, etc. Any ideas what might cause this? I fully expect it to be a silly mistake on my part ;)

Thanks in advance!

**Comment by feross** [comment]
The tracker responds with this message when a peer sends an HTTP request to the tracker that is missing a port parameter, or that has an invalid port parameter. If everything is working fine with your torrent client and you're able to download the torrent, then the error can be safely ignored.

It's possible that the Deluge client is sending a test request to the tracker that is missing the port parameter before it sends a real request. No idea why it would do this, but the warning is just informational.
