### ISSUE TITLE
Merge uWebTorrentTracker back into this package?

### ISSUE THREAD

**Issue by feross** [webtorrent/bittorrent-tracker#269]
Is it worth looking into getting [uWebTorrentTracker](https://github.com/DiegoRBaquero/uWebTorrentTracker) merged back into this package? Or is the goal too different? There's an argument to be made either way:

Separate – having the spec operating as two implementations ensures that any single implementation isn't the de-facto standard, but rather the spec is the standard.

Together – save maintenance effort / confusion for newcomers.

Curious to hear your thoughts, @DiegoRBaquero

**Comment by DiegoRBaquero** [comment]
The only difference, I think, is that uwt uses uws instead of ws. Spec should remain the same. It's just that uws is much more performant. Maybe make it an option here?

**Comment by feross** [comment]
Do we have some way to measure the current performance difference, like a benchmark suite? I think `ws` has tried to improve performance recently so it's worth double checking before switching modules.

**Comment by DiegoRBaquero** [comment]
@feross thoughts?

**Comment by alxhotel** [comment]
I tested the change from `ws` to `uws` and it uses at least 2 times less memory and much less CPU. I don't have any benchmarks, but I can confidently say that `uws` is a good improvement.

**Comment by DiegoRBaquero** [comment]
I've archived uwt and will work on bittorrent-tracker from now on. I can see GREAT improvements in ws since I released uwt, but still, uWebSockets should be better. Will get to it when I have time

**Comment by feross** [comment]
@DiegoRBaquero Thanks for the update. You might have interest in the new backend design that @alxhotel has been considering: https://github.com/webtorrent/bittorrent-tracker/issues/354 I'm sure he'd love your feedback if you time in that issue.
