### ISSUE TITLE
ssl support?

### ISSUE THREAD

**Issue by misaka00251** [webtorrent/bittorrent-tracker#276]
Tried nginx `proxy_pass` with no luck.
Web status page is working but my client always said "Could not connect to tracker".

**Comment by DiegoRBaquero** [comment]
Can you post your nginx config?

**Comment by feross** [comment]
I'm going to close this issue because `bittorrent-tracker` doesn't support SSL, so this isn't an issue with this package. However, feel free to continue discussion and share your nginx config with @DiegoRBaquero.
