### ISSUE TITLE
Usage bittorrent-tracker + webtorrent

### ISSUE THREAD

**Issue by GooG2e** [webtorrent/bittorrent-tracker#277]
Hello!
I am trying to use webtorrent + bittorent-tracker, but if I write ws protocol in torrent then webtorrent doesn't connect
if write wss then it writes error
Can you help with this?

**Comment by DiegoRBaquero** [comment]
Hi @GooG2e , if you are using webtorrent in an https website, then tracker must be in wss (https) too.

wss is a websocket over https connection, so you must use a valid certificate. Lets Encrypt is free.

**Comment by GooG2e** [comment]
But I didn't find any options for this in cli interface 
Or I must do this using nginx or apache?

**Comment by DiegoRBaquero** [comment]
You must use a reverse proxy. I'd suggest nginx
