### ISSUE TITLE
Can't start with Windows Node.js

### ISSUE THREAD

**Issue by tenent007963** [webtorrent/bittorrent-tracker#278]
I have a Windows Server 2008 with latest Node.js installed,I first tried open a new folder and execute `npm install bittorrent-tracker` and the folder pop up a "node_modules" folder and a "package_lock.json" file. After this, I download the whole repo, copy to the root folder, and run `npm install`.This time,it DID installed successfully but when trying to start by execute `bittorrent-tracker` in cmd it returns command not found. Tried `npm start bittorrent-tracker` and can't access by localhost:8000.

**Comment by DiegoRBaquero** [comment]
Maybe `bittorrent-tracker.cmd` ? I don't really have any experience on Windows and how binaries are installed.

**Comment by No9** [comment]
Hey @tenent007963 
If you want to install it as a server application you have to do add the `-g` comand
```
npm install -g bittorrent-tracker
```
Then run it with 
```
bittorrent-tracker
```
Full details here 
https://github.com/webtorrent/bittorrent-tracker#command-line

**Comment by DiegoRBaquero** [comment]
OMG. I missed to notice that he installed as a local dependency.

Thank you @No9 ! 

@tenent007963, you should install as a global command.

I'm gonna close this now, but feel free to comment if you can't get it running.

**Comment by tenent007963** [comment]
Ah, forget to mention I too install it with `-g` option.
At last, I fix it. Just move all packages from repo to the "node_modules" folder and run `npx bittorrent-tracker`.
Anyway thanks for helping.
