### ISSUE TITLE
ISP swarm peers

### ISSUE THREAD

**Issue by hoangtrongphuc** [webtorrent/bittorrent-tracker#279]
How can I group peers based location and ISP of peer.
Do you suggest for me efficiently topology for peers list in swarm ?
Thank you !

**Comment by DiegoRBaquero** [comment]
group for what? stats?

Maybe by subnet closiness, that would be my approach

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
