### ISSUE TITLE
get peer IP addresses from bittorrent-tracker?

### ISSUE THREAD

**Issue by k0a1a** [webtorrent/bittorrent-tracker#287]
hi, 

by reading http://bittorrent.org/beps/bep_0003.html i see how peers' IP addresses are passed around, 
however - would would be the way of getting this information from bittorrent-tracker?
any pointers are much appreciated ,)

**Comment by DiegoRBaquero** [comment]
Each peer in each swarm has the ip. See https://github.com/webtorrent/bittorrent-tracker/blob/master/server.js#L223
