### ISSUE TITLE
Add tls support

### ISSUE THREAD

**Issue by ghost** [webtorrent/bittorrent-tracker#290]

**Comment by DiegoRBaquero** [comment]
Unnecessary imho, just put it behind a proxy such as nginx. Works perfectly :)

**Comment by psharma04** [comment]
Is there no intention of adding native SSL/TLS support?

**Comment by feross** [comment]
Correct. We have limited resources and it's not worth the added complexity of supporting TLS here when the best practice is to deploy Node.js behind a proxy server like `nginx` in production anyway.
