### ISSUE TITLE
Load balancing for bittorrent-tracker?

### ISSUE THREAD

**Issue by brooklyn097** [webtorrent/bittorrent-tracker#299]
Hi, this could be a dumb question but is there a way to do balancing for the tracker?

Thanks for reading!

**Comment by DiegoRBaquero** [comment]
Not at the moment as the peers are tracked in memory. Something like redis would need to be the store first

**Comment by brooklyn097** [comment]
@DiegoRBaquero Thanks for your answer. Btw, is it possible to use 0.0.0.0 address for server listening? I've tried and saw this message on error event when start the application:

> bind EINVAL 0.0.0.0:

But I still accessible to /stats page so i don't know whether there is any error cause by this.

**Comment by brooklyn097** [comment]
Yes you’re right! It shown an error but it actually work fine.

**Comment by mullerivan** [comment]
@brooklyn097 I have a  tracker  that user  redis  on  to scale and  balance the load  on several servers 
hit me an email mullerivan@gmail.com

**Comment by mrlika** [comment]
We decided to create our own open source high-performance implementation of WebTorrent tracker: https://github.com/Novage/wt-tracker

Our tests show that to handle 100k peers (no SSL) it requires 1.2Gb of memory and 50% of a single CPU core.

It is written using [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js) that allows efficiently process WebSockets connections and optimized alorithms that use less CPU than other similar trackers.

**Comment by brooklyn097** [comment]
> We decided to create our own open source high-performance implementation of WebTorrent tracker: https://github.com/Novage/wt-tracker
> 
> Our tests show that to handle 100k peers (no SSL) it requires 1.2Gb of memory and 50% of a single CPU core.
> 
> It is written using [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js) that allows efficiently process WebSockets connections and optimized algorithms that use less CPU than other similar trackers.
> 
> Waiting for your feedback.

Cool, let's test!!!

**Comment by alxhotel** [comment]
Closing in favor of #354
