### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by thenikin** [webtorrent/bittorrent-tracker#301]
Hello, i have installed and im running the tracker with http. Everything looks good but when im trying to actually use it, i get this following error:

`Access` to fetch at 'http://mywebsite.com from origin 'http://mywebsite.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. ``

I have tried installing the npm cors package without luck as im not sure where the headers go. Anyone faced something similar? Shoud i just run a transparent proxy with nginx to fix this issue?

Thanks

**Comment by DiegoRBaquero** [comment]
Yes, use nginx proxy in front of the tracker :)
