### ISSUE TITLE
Request timeout settings

### ISSUE THREAD

**Issue by XJIOP** [webtorrent/bittorrent-tracker#311]
how to override REQUEST_TIMEOUT ? it was nice to be able to set this value in client options.

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this. If you would like to see it fixed, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
