### ISSUE TITLE
Peer list filter

### ISSUE THREAD

**Issue by orifinkelman** [webtorrent/bittorrent-tracker#313]
Hi,
Is there a way to filter the peer list returned by the tracker using my own filter logic? or the only way to do it is by changing response.peers in the announce function?
I'm considering adding a peer filter function to the server and use it in the announce to filter on the peers in the swarm.

**Comment by alxhotel** [comment]
There is already a `filter` function in the `_onAnnounce` function ([here](https://github.com/webtorrent/bittorrent-tracker/blob/master/server.js#L33)) that is applied every time it receives a `announce` request.

You can customize this filter by passing a function in the parameters of `Server`.
