### ISSUE TITLE
https://openwebtorrent.com/ is down for a few days

### ISSUE THREAD

**Issue by mrlika** [webtorrent/bittorrent-tracker#317]

**Comment by DiegoRBaquero** [comment]
@alxhotel

**Comment by alxhotel** [comment]
My bad. The server has been receiving a high amount of traffic, lately.

I'm trying to write a quick integration of Redis in the spirit of having an autoscaling tracker. I see there are already issues (ex. #299) in this direction. Let me know if anyone has already started doing this kind of integration.

But in the meantime I have upgraded the server. It should be working now.
