### ISSUE TITLE
Client   get  server Ip address

### ISSUE THREAD

**Issue by mullerivan** [webtorrent/bittorrent-tracker#322]
Hi there  how  should i  get the Real IP addres of the  TRACKER SERVER after i start  it  from the client
Lets say  after or  before

>         const ops = {
>             infoHash: Buffer.from(this.info_hash, 0, 20),
>             peerId: Buffer.from(this.peerId,0,20),
>             announce: ['my.tracker.com'],
>             rtcConfig: rtcConfig,
>             port: 6881 // a dummy value allows running in Node.js environment
> this.Client = new Client(ops);
> this.Client.start();
>

**Comment by feross** [comment]
Usually, this information is not available directly to the server in an easy way. Usually you should know the IP address of your server and it should never change. 

However, you could also determine the IP at runtime by pinging a service like https://www.ipify.org which will respond with what IP address the request came from.
