### ISSUE TITLE
tracker IPV6 UDP Don't work

### ISSUE THREAD

**Issue by lirener** [webtorrent/bittorrent-tracker#335]
**What version of this package are you using?**
latest version：9.14.4
**What operating system, Node.js, and npm version?**
system：windows10（win10）
npm：5.5.1
**What happened?**
tracker IPV6 UDP Don't work!~
**What did you expect to happen?**
Fix the BUG
**Are you willing to submit a pull request to fix this bug?**
yes!~

<a href="https://ibb.co/DCyNSwf"><img src="https://i.ibb.co/KqkY3Vx/IPV6-UDP-error.jpg" alt="IPV6-UDP-error" border="0" /></a>

**Comment by lirener** [comment]
qBittorrent：
极个别工作（Very few work）
<a href="https://imgchr.com/i/Mxwx4s"><img src="https://s2.ax1x.com/2019/11/26/Mxwx4s.md.jpg" alt="Mxwx4s.jpg" border="0" /></a>
uTorrent：
全部罢工=不工作（All the strike = does not work）
<a href="https://imgchr.com/i/MxwvNj"><img src="https://s2.ax1x.com/2019/11/26/MxwvNj.md.jpg" alt="MxwvNj.jpg" border="0" /></a>
server：
<a href="https://imgchr.com/i/MxwjEQ"><img src="https://s2.ax1x.com/2019/11/26/MxwjEQ.md.jpg" alt="MxwjEQ.jpg" border="0" /></a>

端口监听正常……但是他们就是无法工作 在IPV6 UDP上
（Ports for normal...But they just can't work on IPV6 UDP）

**Comment by lirener** [comment]
IPV6 UDP No Port？
<a href="https://ibb.co/S0xGnH1"><img src="https://i.ibb.co/bL3DBYy/IPV6-UDP-NO-port.jpg" alt="IPV6-UDP-NO-port" border="0" /></a>

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please send a pull request with your suggested fix and we'll be happy to review it.
