### ISSUE TITLE
URL parsing bug in client.js 

### ISSUE THREAD

**Issue by zanhesl** [webtorrent/bittorrent-tracker#352]
**What version of this package are you using?**
latest
**What operating system, Node.js, and npm version?**
npm@6.14.4 Node.js v12.16.3
**What happened?**
On the remote PC's with ubuntu/windows server an error occur, when library tries to parse URL of custom announced tracker.
<img width="524" alt="Снимок экрана 2020-06-11 в 16 09 02" src="https://user-images.githubusercontent.com/48605213/84388821-df522680-abfd-11ea-8f82-df05b649608a.png">
Happens in this catcher:
<img width="617" alt="Снимок экрана 2020-06-11 в 16 10 09" src="https://user-images.githubusercontent.com/48605213/84388921-07da2080-abfe-11ea-8d88-f3aff47620cb.png">
at the line 88.
**What did you expect to happen?**
Adding torrent like normal.
**Solution**
add
`const URL = require('url').URL;`
at the start of bittorent-tracker/client.js file

**Comment by alxhotel** [comment]
Hi @zanhesl,

Can you show an example of a URL tracker you are trying to use?

(Also the first screenshot you posted is only a warning, so that shouldn't be a problem)

**Comment by Fabiencdp** [comment]
It concern any url. 
the real error is : TypeError: URL is not a constructor
the tracker announce url simply cannot be parsed.

Maybe because the author use React, Meteor, or any ?
See https://github.com/nodejs/help/issues/2311

**Comment by feross** [comment]
Please use Node v10 or later where the `URL` object is available on the global.
