### ISSUE TITLE
few files

### ISSUE THREAD

**Issue by Slender1808** [webtorrent/bittorrent-tracker#353]
is it possible to limit tracker to just a few files ?

**Comment by alxhotel** [comment]
Hi @Slender1808,

What do you mean?

The tracker only knows about the infohash of the torrent, not the files.

**Comment by Slender1808** [comment]
like passing a hash list that the tracker will accept

**Comment by alxhotel** [comment]
Ah ok.

You can already limit the hashes that the tracker accepts by using the `filter` function inside the constructor.

Checkout https://github.com/webtorrent/bittorrent-tracker#server

**Comment by Slender1808** [comment]
> Ah ok.
> 
> You can already limit the hashes that the tracker accepts by using the `filter` function inside the constructor.
> 
> Checkout https://github.com/webtorrent/bittorrent-tracker#server

is it possible to pass a list to the filter ?

**Comment by alxhotel** [comment]
You can specify a list like this:

```js
// My list of allowed infohashes
const myList = [
  'aaa67059ed6bd08362da625b3ae77f6f4a075aaa',
  '08ada5a7a6183aae1e09d831df6748d566095a10'
];

const server = new Server({
  filter: function (infoHash, params, cb) {
    if (myList.includes(infoHash)) {
      // If the callback is passed `null`, the torrent will be allowed.
      cb(null)
    } else {
      // If the callback is passed an `Error` object, the torrent will be disallowed
      // and the error's `message` property will be given as the reason.
      cb(new Error('disallowed torrent'))
    }
  }
})
```
