### ISSUE TITLE
Browserify example not producing expected results

### ISSUE THREAD

**Issue by KeeJef** [webtorrent/bittorrent-tracker#359]
**What version of this package are you using?**

9.16.1

**What operating system, Node.js, and npm version?**

NPM Version 6.14.10

**What happened?**

I'm trying to follow the example guide you have posted [here](https://github.com/webtorrent/bittorrent-tracker/blob/master/examples/tracker-scrape.md) to get the bittorent-tracker working to scrape data from trackers from inside the browser. However following the guide exactly seems to produce no console output. 

I can get scraping to work locally with NodeJS just fine, but as soon as i go and try to use Browserify to get this functionality working in the browser it fails to produce any console output. It does seem that guide is quite old, maybe there is a better way of doing this now? 

**What did you expect to happen?**

I expected tracker information to be printed into the console of my browser, however nothing appeared

**Are you willing to submit a pull request to fix this bug?**

I don't think I would know where to start,

**Comment by alxhotel** [comment]
Hi @KeeJef,

I have tested the script and it's working fine.

**Note**: In the browser, the `bittorrent-tracker` client will only use the websocket trackers. Since it can not connect to UDP trackers and the HTTP trackers return bittorrent peers.
