### ISSUE TITLE
Question about warning: "no peer with that `to_peer_id`"

### ISSUE THREAD

**Issue by geco** [webtorrent/bittorrent-tracker#384]
https://github.com/webtorrent/bittorrent-tracker/blob/ff20a05e4830dd62df16da0a549e69ae96843b4d/server.js#L554

We are using peertube into a live env, and it raises a lot of errors of this type: "Error: no peer with that `to_peer_id`".

In a "normal" situation, when this error should be raised? Which scenario represents? A peer disconnected? Some firewall truncated connection?

NodeJS version: 14.17.1
"bittorrent-tracker": "^9.0.0"

Thanks

**Comment by alxhotel** [comment]
Hi @geco,

This event usually happens when the peer has been disconnected before the message could be passed to him.

This happens either because the peer has disconnected or because the server has closed the connection with that peer due to a bad message or bad peer id.
