### ISSUE TITLE
Make HTTPTracker available in browser?

### ISSUE THREAD

**Issue by zckevin** [webtorrent/bittorrent-tracker#406]
**What version of this package are you using?**

**What problem do you want to solve?**
Now I'm using Webtorrent + WebRTC for torrent streaming, and HTTPTracker is only available
in node env, maybe we could make it available in browser?

**What do you think is the correct solution to this problem?**
Just move some code from common-node.js to common.js.

**Are you willing to submit a pull request to implement this change?**
Sure

**Comment by alxhotel** [comment]
The HTTP bittorrent tracker protocol, although available in the browser, is meant for TCP clients that can open arbitrary ports. The browser can not make such connections.

So, I think, for HTTP to be supported in the browser clients, the bittorrent tracker protocol should be updated.
