### ISSUE TITLE
npm versions > 10.0.8 will not run due to bug in simple-peer lite

### ISSUE THREAD

**Issue by MasterEvilAce** [webtorrent/bittorrent-tracker#488]
I am using bittorrent-tracker via NPM and for versions newer than 10.0.8 the script is generating an error and does not run.

file:///usr/local/lib/node_modules/bittorrent-tracker/node_modules/@thaunknown/simple-peer/lite.js:513
          if (!this.initiator) this._requestMissingTransceivers?.()

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)

**Comment by ThaUnknown** [comment]
thats an issue with your AST parser used by your bundler, or outdated version of node, this is valid syntax, its modern syntax, so it might be unsupported by older engines, at which point i'd recommend transpiling the lib using webpack
