### ISSUE TITLE
No "exports" main defined in C:\cygwin64\home\pguar\node\tv\node_modules\bittorrent-tracker\package.json

### ISSUE THREAD

**Issue by pguardiario** [webtorrent/bittorrent-tracker#537]
`const Tracker = require('bittorrent-tracker')
`
What am I doing wrong here please? I realize there is some module / non  module nonsense that happens with some node libraries, but it's rare and it seems surmountable. Can someone offer any direction on this one?

**Comment by SilentBot1** [comment]
Hey @pguardiario, 

In ESM you can do:
```js
import { Client } from 'bittorrent-tracker';
```

In CJS you can do: 
```js
const main = async () => {
    const { Client } = await import('bittorrent-tracker')
    console.log(Client)
}

main()
```

This if you are using CJS or ESM depends on your file extension `.mjs` vs `.js` or your package.json's `type` property.
